apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: red-gitopscluster
  namespace: acm-gitops-policy
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: red-gitopscluster
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: redclusterset
                  namespace: redargocd
                spec:
                  clusterSet: redclusterset
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: red-placement
                  namespace: redargocd
                spec:
                  clusterSets:
                    - redclusterset
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1beta1
                kind: GitOpsCluster
                metadata:
                  name: red-gitops
                  namespace: redargocd
                spec:
                  argoServer:
                    cluster: local-cluster
                    argoNamespace: redargocd
                  placementRef:
                    name: red-placement
                    namespace: redargocd
                    kind: Placement
                    apiVersion: cluster.open-cluster-management.io/v1beta1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: red-gitopscluster-placement
  namespace: acm-gitops-policy
spec:
  clusterSelector:
    matchExpressions:
      - key: cluster.open-cluster-management.io/clusterset
        operator: In
        values:
          - default
  clusterConditions: []
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: red-gitopscluster-placement
  namespace: acm-gitops-policy
placementRef:
  name: red-gitopscluster-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: red-gitopscluster
    kind: Policy
    apiGroup: policy.open-cluster-management.io
