apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fleetPlatformAppset.yaml
  - blueTeamAppProject.yaml
  - redTeamAppProject.yaml
  - blueMobileAppset.yaml
  - redGalagaAppset.yaml
