apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mobile-application-set-fixed
  namespace: blueargocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            cluster.open-cluster-management.io/clusterset: blueclusterset
        values:
          revision: main
  template:
    metadata:
      name: mobileapp-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/rokej/BlueApplications.git
        targetRevision: "{{values.revision}}"
        path: mobileApplication
      destination:
        namespace: mobileapp
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
