apiVersion: v1
kind: Namespace
metadata:
  name: redargocd
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: redargocd
  namespace: redargocd
spec:
  # This enables the application set controller
  applicationSet: {}
  # This enables the ArgoCD instance to use OpenShift OAuth
  dex:
    openShiftOAuth: true
  server:
    route:
      enabled: true