apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - InstallGitOpsOperator
  - FleetArgoCD
  - RegisterAllClustersToFleet
  - ClusterSets/blueclusterset
  - ClusterSets/redclusterset
