apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationset-placement-reader
  labels:
    app.kubernetes.io/component: applicationset
    app.kubernetes.io/name: argocd-applicationset
    app.kubernetes.io/part-of: argocd
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placementdecisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
